
FROM python:3.8.0-slim

# Environment Variables
	ENV PYTHONUNBUFFERED 1
	ENV PYTHONDONTWRITEBYTECODE 1

# Install Project Requirements
	RUN mkdir /code
	WORKDIR /code
	RUN pip install --upgrade pip
	COPY requirements.txt /code/
	RUN pip install -r requirements.txt

# Add The Source
	COPY . /code/

ENTRYPOINT ["/code/entrypoint-dev.sh"]
