# Generated by Django 2.2 on 2020-06-13 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_plugins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test1',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_plugins_test1', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
