# Generated by Django 2.2 on 2020-06-13 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=128)),
                ('city', models.CharField(default='', max_length=64)),
                ('state', localflavor.us.models.USStateField(default='TX', max_length=2)),
                ('zip_code', localflavor.us.models.USZipCodeField(default='', max_length=10)),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(default='+1', max_length=128, null=True, region=None)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
