# Generated by Django 2.2 on 2020-06-13 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_auto_20200613_1650'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
