# Generated by Django 2.2 on 2020-06-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerapplication',
            name='volunteer_type',
            field=models.CharField(choices=[('Direct Patient Care Activities', 'Direct Patient Care Activities – working directly with the patients and their families (may include patient visitation, caregiver respite, telephone contacts, errands, etc.)'), ('Indirect Patient Activities', 'Indirect Patient Activities - not working directly with the patients (may include yard work, pet care, light construction, sewing, baking, treats/gifts, projects, etc.)'), ('Administrative Activities', 'Administrative Activities (may include typing, mailings, filing, phone support, copying, faxing, special projects, etc.)')], default=None, max_length=40, null=True),
        ),
    ]
