# Generated by Django 2.2 on 2020-06-13 23:58

from django.db import migrations, models
import localflavor.us.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core_forms', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, default='TX', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='street_address',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=localflavor.us.models.USZipCodeField(blank=True, default='', max_length=10, null=True),
        ),
    ]
